package org.stypox.dicio.output.graphical

import android.view.View
import org.dicio.skill.util.CleanableUp

/**
 * An interface that has to be implemented by classes that wish to display the output generated by
 * skills
 */
interface GraphicalOutputDevice : CleanableUp {
    /**
     * Displays graphical output to the user
     * @param graphicalOutput a view to show, usually encapsulated inside an output container
     */
    fun display(graphicalOutput: View)

    /**
     * Displays temporary graphical output to the user. After either [.display] or
     * this function are called again the temporary output will be removed and replaced with the
     * newly provided one. This should be used, for example, while loading things, so that the
     * loading state can then be removed and replaced by the loaded content.
     * @param graphicalOutput a view to show, usually encapsulated inside an output container, that
     * will be removed whenever a new view is requested to be displayed
     */
    fun displayTemporary(graphicalOutput: View)

    /**
     * Removes the temporary view previously added with [.displayTemporary], if it is
     * present, otherwise does nothing
     */
    fun removeTemporary()

    /**
     * Adds a divider the output to separate between different things. Does not do anything if
     * called before any [.display], since it makes no sense to add a divider as the
     * first view.
     */
    fun addDivider()
}
