package org.dicio.skill.chain

import androidx.annotation.CallSuper
import org.dicio.skill.SkillComponent
import org.dicio.skill.output.SkillOutput
import org.dicio.skill.util.CleanableUp

/**
 * Hosts platform-specific code to produce platform-specific output based on the data obtained from
 * the previous step. Do here all platform-specific things (e.g file accessing,
 * preference handling, etc.).
 * @param FromType the type of the data generated by the previous step
 */
abstract class OutputGenerator<FromType> : SkillComponent(), CleanableUp {
    /**
     * Generates output to speak or to show to the user based on the data calculated in the previous
     * steps. Do here calculations that require access to platform-specific APIs, such as looking
     * for an app on the user's device.
     *
     * @param data the data to use to generate output, from the previous step
     */
    abstract fun generate(data: FromType): SkillOutput

    /**
    * @see CleanableUp.cleanup
    */
    @CallSuper
    override fun cleanup() {}
}
