package org.dicio.skill.chain;

import android.view.View;

import org.dicio.skill.Skill;
import org.dicio.skill.SkillContext;
import org.dicio.skill.output.GraphicalOutputDevice;
import org.dicio.skill.output.SpeechOutputDevice;
import org.dicio.skill.util.CleanableUp;

import java.util.Collections;
import java.util.List;

/**
 * Hosts platform-specific code to produce platform-specific output based on the data obtained from
 * the previous step. Do here all platform-specific things (e.g file accessing,
 * preference handling, etc.).
 * @param <FromType> the type of the data generated by the previous step
 */
public interface OutputGenerator<FromType> extends CleanableUp {

    /**
     * Generates output to speak or to show to the user based on the data calculated in the previous
     * steps. Do here calculations that require access to platform-specific APIs, such as looking
     * for an app on the user's device.
     *
     * @param data the data to use to generate output, from the previous step
     * @param context the skill context with useful resources, see {@link SkillContext}
     * @param speechOutputDevice use this to tell something short and textual to the user, e.g. "My
     *                           name is Dicio"; see {@link SpeechOutputDevice#speak(String)}
     * @param graphicalOutputDevice use this to show something to the user, such as a panel with an
     *                              image, a title and a description, or search results; see {@link
     *                              GraphicalOutputDevice#display(View)}
     */
    void generate(FromType data,
                  SkillContext context,
                  SpeechOutputDevice speechOutputDevice,
                  GraphicalOutputDevice graphicalOutputDevice);

    /**
     * @return a list of skills to use for the next user input. This is needed to allow providing a
     *         stateful interaction with a set of skills. If the list is empty, and it is by
     *         default, the current stateful conversation is interrupted. This function will be
     *         called after {@link #generate(Object, SkillContext, SpeechOutputDevice,
     *         GraphicalOutputDevice)}, so that the calculated data can be used to choose what to
     *         do.
     */
    default List<Skill> nextSkills() {
        // no next skills by default
        return Collections.emptyList();
    }
}
