package org.dicio.skill.chain;

import androidx.annotation.CallSuper;

import org.dicio.skill.Skill;
import org.dicio.skill.SkillComponent;
import org.dicio.skill.util.CleanableUp;
import org.dicio.skill.util.NextSkills;

import java.util.Collections;
import java.util.List;

/**
 * Hosts platform-specific code to produce platform-specific output based on the data obtained from
 * the previous step. Do here all platform-specific things (e.g file accessing,
 * preference handling, etc.).
 * @param <FromType> the type of the data generated by the previous step
 */
public abstract class OutputGenerator<FromType> extends SkillComponent
        implements NextSkills, CleanableUp {

    // no next skills by default
    private List<Skill> nextSkills = Collections.emptyList();

    /**
     * Generates output to speak or to show to the user based on the data calculated in the previous
     * steps. Do here calculations that require access to platform-specific APIs, such as looking
     * for an app on the user's device.
     *
     * @param data the data to use to generate output, from the previous step
     */
    public abstract void generate(FromType data);

    /**
     * @see NextSkills#nextSkills()
     */
    @Override
    public List<Skill> nextSkills() {
        final List<Skill> skills = nextSkills;
        nextSkills = Collections.emptyList();
        return skills;
    }

    /**
     * @see NextSkills#setNextSkills(List)
     */
    @Override
    public final void setNextSkills(final List<Skill> skills) {
        nextSkills = skills;
    }

    /**
     * Resets the last list of next skills passed to {@link #setNextSkills(List)} to an empty list.
     * Remember to call super if you override.
     * @see CleanableUp#cleanup()
     */
    @Override
    @CallSuper
    public void cleanup() {
        nextSkills = Collections.emptyList();
    }
}
