package org.stypox.dicio.sentencesCompilerPlugin.util

const val SKILL_DEFINITIONS_FILE = "skill_definitions.yml"
const val YML_EXT = ".yml"
const val PACKAGE_NAME = "org.stypox.dicio.sentences"
const val CLASS_NAME = "SkillSentences"
const val FILE_COMMENT = "File autogenerated by SentencesCompilerTask"
