package org.stypox.dicio.sentencesCompilerPlugin

const val PACKAGE_NAME = "org.stypox.dicio.sentences"
const val CLASS_NAME = "SkillSentences"
const val FILE_COMMENT = "File autogenerated by SentencesCompilerTask"
