package org.dicio.skill.output;

import android.view.View;

import androidx.annotation.NonNull;

/**
 * An interface that has to be implemented by classes that wish to
 * display the output generated by skills.<br>
 * TODO Some more methods could be added in the future, for example
 * `clearScreen()`, `addDivider()` or something along those lines.
 */
public interface GraphicalOutputDevice {
    /**
     * Displays graphical output to the user
     * @param graphicalOutput a view to show (usually encapsulates inside an output container)
     */
    void display(@NonNull View graphicalOutput);

    /**
     * Adds a divider the output to separate between different things. Does not do anything if
     * called before any {@link #display(View)}, since it makes no sense to add a divider as the
     * first view.
     */
    void addDivider();
}
