package org.stypox.dicio.unicodeCldrPlugin.util

const val CLDR_REPO = "https://github.com/unicode-org/cldr"
const val CLDR_CHECKOUT_PATH = "checkouts/cldr/"
const val CLDR_LANGUAGES_PATH = "common/main/"
const val PACKAGE_NAME = "org.stypox.dicio.cldr"
const val CLASS_NAME = "CldrLanguages"
const val FILE_COMMENT = "File autogenerated by SentencesCompilerTask"
