package org.dicio.dicio_android.output;

import android.content.Context;

import org.dicio.dicio_android.components.AssistanceComponent;
import org.dicio.dicio_android.output.graphical.GraphicalOutputDevice;
import org.dicio.dicio_android.output.speech.SpeechOutputDevice;

import java.util.Collections;
import java.util.List;

/**
 * Hosts platform-specific code to produce platform-specific output based on the data obtained from
 * the previous step. Do here all platform-specific things (e.g file accessing,
 * preference handling, etc.).
 * @param <FromType> the type of the data generated by the previous step
 */
public interface OutputGenerator<FromType> {

    void generate(FromType data,
                  Context context,
                  SpeechOutputDevice speechOutputDevice,
                  GraphicalOutputDevice graphicalOutputDevice);

    /**
     * Returns a list of assistance components to use for the next user input. This is needed to
     * allow providing a stateful interaction with a set of assistance components. If the list is
     * empty the current stateful conversation is interrupted. The function will be called after
     * {@link #generate(Object, Context, SpeechOutputDevice, GraphicalOutputDevice) generate()), so
     * that the calculated data can be used to choose what to do.
     * @return a list of assistance components
     */
    default List<AssistanceComponent> nextAssistanceComponents() {
        // no next components by default
        return Collections.emptyList();
    }
}
